//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMISystemManagemenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public string Devcode { get; set; }
        public string time { get; set; }
        public string idMer { get; set; }
        public int idDC { get; set; }
    
        public virtual Device Devices1 { get; set; }
        public virtual Device Device1 { get; set; }
    }
}
